# https://taskfile.dev

version: '3'

tasks:
  helloworld:
    desc: Hello world
    cmds:
      - go run cmd/helloworld/main.go
    silent: true
  
  values:
    desc: Values chapter
    cmds:
      - go run cmd/values/main.go
    silent: true
