# https://taskfile.dev

version: '3'

tasks:
  newchap:
    desc: Creates a new chapter folder and main file
    cmds:
      - git checkout -b {{.NAME}}
      - mkdir cmd/{{.NAME}}
      - touch cmd/{{.NAME}}/main.go
      - echo "// cmd/{{.NAME}}/main.go" >> cmd/{{.NAME}}/main.go
      - echo "package main" >> cmd/{{.NAME}}/main.go
      - echo "" >> cmd/{{.NAME}}/main.go
      - echo "func main() {}" >> cmd/{{.NAME}}/main.go
  
  endchap:
    desc: Finish a chapter, commit and merge to main
    cmds:
      - git add .
      - git commit -S -s -m {{.CLI_ARGS}}
      - git checkout main
      - git merge {{.NAME}}
      - git push
    silent: true

  chap:
    desc: Runs the code of a given chapter
    cmds:
      - go run cmd/{{.CLI_ARGS}}/main.go
