# https://taskfile.dev

version: '3'

tasks:
  newchap:
    desc: Creates a new chapter folder and main file
    cmds:
      - git checkout -b {{.CLI_ARGS}}
      - mkdir cmd/{{.CLI_ARGS}}
      - touch cmd/{{.CLI_ARGS}}/main.go
      - echo "// cmd/{{.CLI_ARGS}}/main.go" >> cmd/{{.CLI_ARGS}}/main.go
      - echo "package main" >> cmd/{{.CLI_ARGS}}/main.go
      - echo "" >> cmd/{{.CLI_ARGS}}/main.go
      - echo "func main() {}" >> cmd/{{.CLI_ARGS}}/main.go
  
  endchap:
    desc: Finish a chapter, commit and merge to main
    cmds:
      - git add .
      - git commit -S -s -m {{.CLI_ARGS}}
      - git checkout main
      - git merge {{.NAME}}
      - git push
    silent: true

  runchap:
    desc: Runs the code of a given chapter
    dir: cmd/{{.CLI_ARGS}}
    cmds:
      - go run main.go

  testchap:
    desc: Runs tests for a given chapter
    dir: cmd/{{.CLI_ARGS}}
    cmds:
      - go test -v