# https://taskfile.dev

version: '3'

tasks:
  newchap:
    desc: Creates a new chapter folder and main file
    cmds:
      - git checkout -b {{.NAME}}
      - mkdir cmd/{{.NAME}}
      - touch cmd/{{.NAME}}/main.go
      - echo "package main" >> cmd/{{.NAME}}/main.go
      - echo "func main() {}" >> cmd//{{.NAME}}/main.go

  endchap:
    desc: Finish a chapter, commit and merge to main
    cmds:
      - git add .
      - git commit -S -s -m {{.CLI_ARGS}}
      - git checkout main
      - git merge {{.NAME}}
      - git push
    silent: true

  helloworld: go run cmd/helloworld/main.go
    
  values: go run cmd/values/main.go
    
  variables: go run cmd/variables/main.go

  constants: go run cmd/constants/main.go

  for: go run cmd/for/main.go

  ifelse: go run cmd/ifelse/main.go

  switch: go run cmd/switch/main.go

  arrays: go run cmd/arrays/main.go

  slices: go run cmd/slices/main.go